version: '2'
services:
  wordpress:
    image: wordpress:4.7.2-php7.1-apache
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=password
    volumes:
      - /opt/docker-volumes/spikewpcache:/var/lib/mysql
  nginx:
    image: nginx-with-purge
    build:
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /opt/docker-volumes/spikenginxcache:/var/lib/nginx_cache
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        aliases:
          - nginx.service
    restart: always